import React, { Component } from 'react';
import { Link } from 'react-router-dom';

export default class Cubeland_Solution_Path extends Component{
	render(){
		return(
			<div style={{paddingLeft: 80, color: 'red', backgroundColor: 'yellow', fontFamily:'Arial'}}>
				<p style={{textAlign: 'left'}}><strong>SPOILER ALERT </strong></p>
				<p style={{textAlign: 'left'}}>(If you find yourself lost and don’t have the time to ponder the cube to get your keys back)</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Solution path through Cubeland:</p>
				<p style={{textAlign: 'left'}}>Door directions to take</p>
				<p style={{textAlign: 'left'}}><strong>D, R, D, U, O, U, R, L, D, I, L, U, L, D, I, U, L, R, R, I, D, O, D, U, R, I, R, D, O, O, R, O, R</strong> </p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Cubeland is 27 rooms connected together like the vertices of a cube.</p>
				<p style={{textAlign: 'left'}}>If you travel to the edge of the cube in whichever direction, you will emerge at the opposite side room of the cube. For instance, if you were in the middle furthest to the left room of the cube and went through the left door, you would enter the room in the middle furthest to the right room of the cube. The same logic applies for up/down and in/out</p>
				<p style={{textAlign: 'left'}}>In/out doors (in in the right middle of the rooms, out in the left middle of the rooms) move you in the z direction of the cube.</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>The player's position in the cube is represented by a map at the top left corner of the screen and as the background of each room.</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Start in room 0_0_0&nbsp;&nbsp;</p>
				<p style={{textAlign: 'left'}}>will need to get to the <strong>down</strong> door of the room</p>
				<p style={{textAlign: 'left'}}>Solution:&nbsp;</p>
				<p style={{textAlign: 'left'}}>go ahead and collect powerup at bottom,&nbsp;</p>
				<p style={{textAlign: 'left'}}>go to middle right of level and flip switch above right door,&nbsp;</p>
				<p style={{textAlign: 'left'}}>go down through opening, go left on 2nd from bottom level pass through opening before stone barricade is reset</p>
				<p style={{textAlign: 'left'}}>flip switch on the left wall</p>
				<p style={{textAlign: 'left'}}>go one level up, move toward right and flip switch, get through opening before stone barricade is reset&nbsp;</p>
				<p style={{textAlign: 'left'}}>go to right and then all the way to bottom of level</p>
				<p style={{textAlign: 'left'}}>move to the left before the stone barricade by the down door is reset</p>
				<p style={{textAlign: 'left'}}>go through down door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 1_0_0</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>right</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>enter room at top</p>
				<p style={{textAlign: 'left'}}>go down through opening immediately to the left</p>
				<p style={{textAlign: 'left'}}>move toward door to the right of room</p>
				<p style={{textAlign: 'left'}}>there are health supplements scattered throughout room and lots at bottom of the room</p>
				<p style={{textAlign: 'left'}}>can flip switch on lower right wall to enable a platform to be able to access the other platforms and get the health supplements - can do this before leaving through right door if you need health</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 1_1_0&nbsp;</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>down</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go towards bottom left of room and flip switch&nbsp;</p>
				<p style={{textAlign: 'left'}}>go down and through the bottom door before stone barricade is reset</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 2_1_0</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>in</strong> door in the room TO COLLECT DOUBLE JUMP POWERUP IN ROOM 2_1_1</p>
				<p style={{textAlign: 'left'}}>Solution:&nbsp;</p>
				<p style={{textAlign: 'left'}}>left, down through opening</p>
				<p style={{textAlign: 'left'}}>right, down through opening</p>
				<p style={{textAlign: 'left'}}>right, down through opening</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 2_1_1</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>out</strong> door AFTER COLLECTING DOUBLE JUMP POWERUP</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go down to platforms down right</p>
				<p style={{textAlign: 'left'}}>go down to platform on left</p>
				<p style={{textAlign: 'left'}}>get double jump powerup</p>
				<p style={{textAlign: 'left'}}>jump back up to door</p>
				<p style={{textAlign: 'left'}}>go through out door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 2_1_0</p>
				<p style={{textAlign: 'left'}}>need to get to the back to <strong>up</strong> door in the room AFTER COLLECTING KEY AA</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>right, down through opening&nbsp;</p>
				<p style={{textAlign: 'left'}}>flip switch to the right</p>
				<p style={{textAlign: 'left'}}>go through opening that opened to the left before reset</p>
				<p style={{textAlign: 'left'}}>get key to the left</p>
				<p style={{textAlign: 'left'}}>right, down through opening to platform immediately below</p>
				<p style={{textAlign: 'left'}}>flip switch to the left</p>
				<p style={{textAlign: 'left'}}>travel back to the right, down through opening</p>
				<p style={{textAlign: 'left'}}>left, up through opening</p>
				<p style={{textAlign: 'left'}}>left, up through opening</p>
				<p style={{textAlign: 'left'}}>right, up through opening before platform resets</p>
				<p style={{textAlign: 'left'}}>left, up through opening</p>
				<p style={{textAlign: 'left'}}>right, up through opening</p>
				<p style={{textAlign: 'left'}}>up through opening immediately to the left</p>
				<p style={{textAlign: 'left'}}>up through opening immediately to the left</p>
				<p style={{textAlign: 'left'}}>climb ladder to the right to exit back through up door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 1_1_0</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>out (left middle)</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>flip switch to the right</p>
				<p style={{textAlign: 'left'}}>left, jump over door, up through opening</p>
				<p style={{textAlign: 'left'}}>climb ladder immediately to the right</p>
				<p style={{textAlign: 'left'}}>go to right&nbsp;</p>
				<p style={{textAlign: 'left'}}>jump on platforms to get to door to your up left visible on screen</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 1_1_2</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>up</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go to right, jump on horizontally moving platform by Bimmy</p>
				<p style={{textAlign: 'left'}}>jump on vertically moving platform to the right</p>
				<p style={{textAlign: 'left'}}>jump on horizontally moving platform to the left</p>
				<p style={{textAlign: 'left'}}>up through the opening&nbsp;</p>
				<p style={{textAlign: 'left'}}>left, up through up door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 0_1_2</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>right</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>climb hill to the right</p>
				<p style={{textAlign: 'left'}}>jump platforms to flip switch on right wall</p>
				<p style={{textAlign: 'left'}}>go down to left to flip switch to the right of the hill</p>
				<p style={{textAlign: 'left'}}>jump on vertically moving platform and jump through opening above before reset</p>
				<p style={{textAlign: 'left'}}>go to the right through the right door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 0_2_2</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>left</strong> door in the room AFTER COLLECTING KEY BB</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>continue down to bottom platform&nbsp;</p>
				<p style={{textAlign: 'left'}}>go to right, up through opening</p>
				<p style={{textAlign: 'left'}}>go to right, down through opening</p>
				<p style={{textAlign: 'left'}}>go to right, continue right over barricade with ladders</p>
				<p style={{textAlign: 'left'}}>climb ladder to the right</p>
				<p style={{textAlign: 'left'}}>go to right, up through opening</p>
				<p style={{textAlign: 'left'}}>go to left, up through opening</p>
				<p style={{textAlign: 'left'}}>go to right, up through opening</p>
				<p style={{textAlign: 'left'}}>continue up to top and get key BB</p>
				<p style={{textAlign: 'left'}}>go all of the way back down (down ladder etc) until you reach barricade with ladders again</p>
				<p style={{textAlign: 'left'}}>go to left over barricade with ladders</p>
				<p style={{textAlign: 'left'}}>go to left, up through opening</p>
				<p style={{textAlign: 'left'}}>go to left, down through opening</p>
				<p style={{textAlign: 'left'}}>go to left, jump on vertically moving platform</p>
				<p style={{textAlign: 'left'}}>up through opening</p>
				<p style={{textAlign: 'left'}}>go through left door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 0_1_2</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>down</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>stand directly underneath vertically moving platform and allow it to push you through the floor</p>
				<p style={{textAlign: 'left'}}>go to left&nbsp;</p>
				<p style={{textAlign: 'left'}}>go through down door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 1_1_2</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>in (right middle)</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go down and slightly to the right</p>
				<p style={{textAlign: 'left'}}>go through in door (the right one of the 2 middle doors)</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 1_1_0</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>left</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go up onto platform above door</p>
				<p style={{textAlign: 'left'}}>jump over switch and fall down to platform below&nbsp;</p>
				<p style={{textAlign: 'left'}}>jump to platform to the left&nbsp;</p>
				<p style={{textAlign: 'left'}}>go through left door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 1_0_0</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>up</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>jump on vertically moving platform to the left</p>
				<p style={{textAlign: 'left'}}>jump on horizontally moving platform above to the left</p>
				<p style={{textAlign: 'left'}}>jump to stable platform to the left</p>
				<p style={{textAlign: 'left'}}>go up through opening</p>
				<p style={{textAlign: 'left'}}>go through up door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 0_0_0</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>left</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go to right</p>
				<p style={{textAlign: 'left'}}>jump on vertically moving platform</p>
				<p style={{textAlign: 'left'}}>go up through opening</p>
				<p style={{textAlign: 'left'}}>go to the left until you see vertically moving platform</p>
				<p style={{textAlign: 'left'}}>jump on vertically moving platform</p>
				<p style={{textAlign: 'left'}}>go right, jump on vertically moving platform</p>
				<p style={{textAlign: 'left'}}>flip switch on right wall</p>
				<p style={{textAlign: 'left'}}>go left, jump on vertically moving&nbsp;</p>
				<p style={{textAlign: 'left'}}>go through opening on the left before stone barricade is reset</p>
				<p style={{textAlign: 'left'}}>go down through openings</p>
				<p style={{textAlign: 'left'}}>go through left door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 0_2_0&nbsp;</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>down</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go down through opening&nbsp;</p>
				<p style={{textAlign: 'left'}}>flip switch on the right</p>
				<p style={{textAlign: 'left'}}>go up through opening</p>
				<p style={{textAlign: 'left'}}>climb ladder on the left</p>
				<p style={{textAlign: 'left'}}>jump on temporary platform and jump to left before temporary platform disappears</p>
				<p style={{textAlign: 'left'}}>jump on platforms to go to the left to ladder</p>
				<p style={{textAlign: 'left'}}>climb ladder</p>
				<p style={{textAlign: 'left'}}>go right up hill&nbsp;</p>
				<p style={{textAlign: 'left'}}>jump on platforms to go right</p>
				<p style={{textAlign: 'left'}}>climb ladder on right wall to get spray shot powerup</p>
				<p style={{textAlign: 'left'}}>go left jumping on same platforms</p>
				<p style={{textAlign: 'left'}}>jump left over ladder&nbsp;</p>
				<p style={{textAlign: 'left'}}>go all of the way to the ground platform</p>
				<p style={{textAlign: 'left'}}>go right, climb hill</p>
				<p style={{textAlign: 'left'}}>go through down door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 1_2_0</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>in (right middle)</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go down and slightly to the right towards the door close to Bimmy</p>
				<p style={{textAlign: 'left'}}>go through in door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 1_2_1</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>up</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>jump on vertically moving platform above door</p>
				<p style={{textAlign: 'left'}}>jump on platform at top to right</p>
				<p style={{textAlign: 'left'}}>go through up door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 0_2_1</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>left</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go left, climb hill</p>
				<p style={{textAlign: 'left'}}>jump on platform on left wall</p>
				<p style={{textAlign: 'left'}}>jump on horizontally moving platform</p>
				<p style={{textAlign: 'left'}}>jump on vertically moving platform</p>
				<p style={{textAlign: 'left'}}>jump on horizontally moving platforms&nbsp;</p>
				<p style={{textAlign: 'left'}}>go through left door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 0_1_1&nbsp;</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>right</strong> door in the room AFTER COLLECTING KEY CC</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go left up through opening</p>
				<p style={{textAlign: 'left'}}>get key CC</p>
				<p style={{textAlign: 'left'}}>go back down, to the right&nbsp;</p>
				<p style={{textAlign: 'left'}}>go through right door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 0_2_1</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>right</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>lots of health supplements accessible at top of room by going to the uppermost left switch and showing platform</p>
				<p style={{textAlign: 'left'}}>jump on platforms to stay up all the way to the right of the room&nbsp;</p>
				<p style={{textAlign: 'left'}}>jump on vertically moving platform to go down&nbsp;</p>
				<p style={{textAlign: 'left'}}>go through right door</p>
				<p style={{textAlign: 'left'}}>also accessible through platform jumping if at the ground level</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 0_0_1&nbsp;</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>in (right middle)</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>you will probably fall all the way to the bottom if you don't move right fast enough</p>
				<p style={{textAlign: 'left'}}>from ground level:</p>
				<p style={{textAlign: 'left'}}>go to the right</p>
				<p style={{textAlign: 'left'}}>jump on vertically moving platform</p>
				<p style={{textAlign: 'left'}}>jump on horizontally moving platform go left</p>
				<p style={{textAlign: 'left'}}>jump on faster horizontally moving platform go left</p>
				<p style={{textAlign: 'left'}}>jump up through opening</p>
				<p style={{textAlign: 'left'}}>jump on horizontally moving platform</p>
				<p style={{textAlign: 'left'}}>jump on stable platform to right&nbsp;</p>
				<p style={{textAlign: 'left'}}>jump on vertically moving platform immediately to right</p>
				<p style={{textAlign: 'left'}}>jump on top platform to right</p>
				<p style={{textAlign: 'left'}}>go to right of room making sure to be able to be at least on platform above door</p>
				<p style={{textAlign: 'left'}}>go all the way to right</p>
				<p style={{textAlign: 'left'}}>go down through opening&nbsp;</p>
				<p style={{textAlign: 'left'}}>flip switch on right wall</p>
				<p style={{textAlign: 'left'}}>go through in door before stone barricade resets</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 0_0_2&nbsp;</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>down</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go right, jump on platforms to get to 2 vertically moving platforms</p>
				<p style={{textAlign: 'left'}}>jump on the rightmost vertically moving platform</p>
				<p style={{textAlign: 'left'}}>flip switch on right wall</p>
				<p style={{textAlign: 'left'}}>go all the way left and down&nbsp;</p>
				<p style={{textAlign: 'left'}}>go down through opening on left before platform resets</p>
				<p style={{textAlign: 'left'}}>go through down door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 1_0_2</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>out (left middle)</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>try not to fall all the way down (if you do it's not the end of the world just get back to the middle door)</p>
				<p style={{textAlign: 'left'}}>land on platform by red dot</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 1_0_1</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>down</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go down</p>
				<p style={{textAlign: 'left'}}>go through down door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 2_0_1</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>up</strong> door in the room AFTER COLLECTING KEY DD</p>
				<p style={{textAlign: 'left'}}>Solution:&nbsp;</p>
				<p style={{textAlign: 'left'}}>go right&nbsp;</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go right&nbsp;</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go left</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go left</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go left</p>
				<p style={{textAlign: 'left'}}>up ladder&nbsp;</p>
				<p style={{textAlign: 'left'}}>go left through first opening</p>
				<p style={{textAlign: 'left'}}>go left</p>
				<p style={{textAlign: 'left'}}>jump on vertically moving platform</p>
				<p style={{textAlign: 'left'}}>jump on platform at top</p>
				<p style={{textAlign: 'left'}}>go right</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go right</p>
				<p style={{textAlign: 'left'}}>up through opening</p>
				<p style={{textAlign: 'left'}}>get key DD</p>
				<p style={{textAlign: 'left'}}>go right</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go left</p>
				<p style={{textAlign: 'left'}}>jump on vertically moving platform</p>
				<p style={{textAlign: 'left'}}>jump on platform at top</p>
				<p style={{textAlign: 'left'}}>go left over ladder barrier</p>
				<p style={{textAlign: 'left'}}>go down through opening</p>
				<p style={{textAlign: 'left'}}>go right</p>
				<p style={{textAlign: 'left'}}>jump on vertically moving platform</p>
				<p style={{textAlign: 'left'}}>go right through opening&nbsp;</p>
				<p style={{textAlign: 'left'}}>go down through opening</p>
				<p style={{textAlign: 'left'}}>go right</p>
				<p style={{textAlign: 'left'}}>go down through opening</p>
				<p style={{textAlign: 'left'}}>go up ladder to right</p>
				<p style={{textAlign: 'left'}}>go up through openings</p>
				<p style={{textAlign: 'left'}}>go right through opening</p>
				<p style={{textAlign: 'left'}}>go up ladders&nbsp;</p>
				<p style={{textAlign: 'left'}}>go through top left opening</p>
				<p style={{textAlign: 'left'}}>go up through openings to top platform</p>
				<p style={{textAlign: 'left'}}>go left</p>
				<p style={{textAlign: 'left'}}>go through up door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 1_0_1</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>right</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>move all the way to the right side of the room to the rightmost door</p>
				<p style={{textAlign: 'left'}}>go through the right door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 1_1_1</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>in (right middle)</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>jump on platforms to get to middle of room</p>
				<p style={{textAlign: 'left'}}>go through the in door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 1_1_2</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>right</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go towards right of room and climb hill</p>
				<p style={{textAlign: 'left'}}>go through right door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 1_2_2</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>down</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go right</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go left</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go right</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go left</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go left&nbsp;</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 2_2_2</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>out (left, middle)</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go right</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go left</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go right</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go left</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go right</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go left</p>
				<p style={{textAlign: 'left'}}>flip switch on stone barricade</p>
				<p style={{textAlign: 'left'}}>down through opening before platform is reset</p>
				<p style={{textAlign: 'left'}}>go left</p>
				<p style={{textAlign: 'left'}}>up through opening</p>
				<p style={{textAlign: 'left'}}>up through opening</p>
				<p style={{textAlign: 'left'}}>up through opening</p>
				<p style={{textAlign: 'left'}}>go right</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go through out door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 2_2_1</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>out (left, middle)</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go down all the way to bottom</p>
				<p style={{textAlign: 'left'}}>jump on platforms to move up and right to the middle left door</p>
				<p style={{textAlign: 'left'}}>go through out door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 2_2_0</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>right</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>go right</p>
				<p style={{textAlign: 'left'}}>go through right door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 2_0_0</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>out (left, middle)</strong> door in the room</p>
				<p style={{textAlign: 'left'}}>Solution:</p>
				<p style={{textAlign: 'left'}}>jump on vertically moving platform</p>
				<p style={{textAlign: 'left'}}>go right through 2nd from top opening</p>
				<p style={{textAlign: 'left'}}>up through opening</p>
				<p style={{textAlign: 'left'}}>up through opening</p>
				<p style={{textAlign: 'left'}}>go right</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>go down as far as the vertically moving platform</p>
				<p style={{textAlign: 'left'}}>go left</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go right</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go right</p>
				<p style={{textAlign: 'left'}}>down through opening</p>
				<p style={{textAlign: 'left'}}>go left</p>
				<p style={{textAlign: 'left'}}>jump on vertically moving platform</p>
				<p style={{textAlign: 'left'}}>go through out door</p>
				<p style={{textAlign: 'left'}}>&nbsp;</p>
				<p style={{textAlign: 'left'}}>Room 2_0_2</p>
				<p style={{textAlign: 'left'}}>need to get to the <strong>right</strong> door in the room</p>
				<p>Solution:</p>
				<p>go right</p>
				<p>jump on vertically moving platform</p>
				<p>down through opening</p>
				<p>go through portal door on right</p>
				<p>jump on vertically moving platform</p>
				<p>go right at top</p>
				<p>jump on vertically moving platform</p>
				<p>go through portal door at top</p>
				<p>go left</p>
				<p>flip switch</p>
				<p>go through portal door down</p>
				<p>go through portal on left (at top left)</p>
				<p>flip switch</p>
				<p>go left</p>
				<p>down through opening before resets</p>
				<p>go right before stone barricade closes from first switch</p>
				<p>go through right door</p>
				<p>&nbsp;</p>
				<p>Room 2_1_2&nbsp;</p>
				<p>fall down&nbsp;</p>
				<p>touch hooded guy</p>
				<p>takes you to bubble boy arena</p>
				<p>you can now fly</p>
				<p>each wall that you come in contact with will transport you to the wall on the opposite side of the arena</p>
				<p>kill all bubble boys and collect the 4 tokens</p>
				<p>a good practice is to go around all 4 to get them to congregate together, then shoot as much as you can before getting hit with bubble boy bullets going through the wall portals repeatedly until able to defeat all bubble boys</p>
				<p>a giant key will emerge, get key, you won!!!!!</p>
				<p>&nbsp;</p>
				<p>&nbsp;</p>
				<p>&nbsp;</p>
				<p>&nbsp;</p>
				<p>&nbsp;</p>
			</div>
		)
	}
}